### ISSUE TITLE
inf-20100420 crashes upon launch

### ISSUE THREAD

**Issue by HalfOfAKebab** [kcxx/RetroWrapper#2]
Not much more to say really. inf-20100415 works fine, but inf-20100420 refuses to launch. I applied exactly the same modifications to both JSONs, so I don't think it's me that's messing up.

It launches fine without RetroWrapper.

**Comment by MisterSheeple** [comment]
Why did you close this?

**Comment by HalfOfAKebab** [comment]
It was a broken JSON.
